version: '3'
services:
  video-processor:
    build:
      context: ./video-processor
      dockerfile: Dockerfile
    runtime: nvidia
    network_mode: host
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - /etc/enctune.conf:/etc/enctune.conf
      - /etc/nv_tegra_release:/etc/nv_tegra_release
      - /tmp/nv_jetson_model:/tmp/nv_jetson_model
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ./video-processor:/app
      # devices:
      #   - /dev/video0:/dev/video0 # Adjust based on your device requirements

    command: python3 src/main.py data/videos/video3.mp4
