services:
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped

  processor:
    build:
      context: ./processor
    restart: unless-stopped

  web:
    build:
      context: ./web
    command: gunicorn -w 1 -b 0.0.0.0:8000 --access-logfile - --error-logfile - app:app
    restart: unless-stopped

  ui:
    build:
      context: ./ui
    restart: unless-stopped

  ntfy:
    restart: unless-stopped
