x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

services:
  nginx:
    container_name: birdlense_nginx
    depends_on:
      - web
      - ui
      - processor
    ports:
      - "80:8080"
      - "8081:8081"
    volumes:
      - ./data:/srv/data
      - /var/lib/docker/containers:/docker_logs:ro # Expose logs in nginx
    logging: *default-logging

  processor:
    container_name: birdlense_processor
    volumes:
      - /dev/shm:/dev/shm # used by audio recording
      - /run/udev:/run/udev:ro
      - "${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse" # pulseaudio proxy
      - "${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie" # pulseaudio proxy
      - ./app_config:/app/src/app_config
      - ./data:/app/data
    devices:
      - /dev/video0 # video
      - /dev/snd # audio
      - /dev/bus/usb # audio
      - /dev/gpiochip0:/dev/gpiochip4 # To address a bug in lgpio described inhttps://github.com/gpiozero/gpiozero/issues/1166
    ipc: host
    environment:
      - API_URL_BASE=http://web:8000/api/processor
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native # pulseaudio proxy
      - LD_LIBRARY_PATH=/opt/vc/lib
    # Command to test pulseaudio setup: "pactl list short sources"
    command: python src/main.py
    privileged: true # unfortunately, it's required for picamera2 to access pi camera
    depends_on:
      - web
    logging: *default-logging

  web:
    container_name: birdlense_web
    depends_on:
      - ntfy
    volumes:
      - /proc:/host/proc:ro # Access CPU/memory stats
      - /sys:/host/sys:ro # Access temperature sensors
      - ./app_config:/app/app_config
      - ./data:/app/data
    logging: *default-logging

  ui:
    container_name: birdlense_ui
    logging: *default-logging

  ntfy:
    container_name: birdlense_ntfy
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      TZ: "America/New_York" # optional: set desired timezone
      NTFY_BEHIND_PROXY: "true"
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
      NTFY_BASE_URL: "http://birdlense.local:8081"
    logging: *default-logging
