services:
  nginx:
    restart: always
    depends_on:
      - web
      - ui
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '80:8080'
    volumes:
      - ./data:/srv/data

  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile.dev
    volumes:
      - /dev/shm:/dev/shm # used by audio recording
      - /run/udev:/run/udev:ro
      - ./processor:/app
      - ./app_config:/app/src/app_config
      - ./data:/app/data
    devices:
      - /dev/video0 # video
      - /dev/snd # audio
      - /dev/bus/usb # audio
    ipc: host
    environment:
      - API_URL_BASE=http://web:8000/api/processor
      - LD_LIBRARY_PATH=/opt/vc/lib
    command: python3 src/main.py data/samples/videos/cardinal.mp4
    # command: python3 src/main.py
    privileged: true
    depends_on:
      - web

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - ./web:/app
      - ./app_config:/app/app_config
      - ./data:/app/data
    command: flask run --host=0.0.0.0 --port=8000 --debug

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./ui:/app
      - ./app_config:/app/app_config
      - ./data:/app/data
